name: buildTestingMacOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-10.15
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer
    steps:
      - name: Cloning Git repository
        uses: actions/checkout@v1
        with:
          submodules: 'recursive'
      - name: Attempt to build the Live Enhancement Suite for macOS
        run: |
          make
